mutation AddWorker($addWorkerData: AddWorkerDTO!) {
    addWorker(addWorkerData: $addWorkerData){
        id
        username
        email
        group
        status
        offerByUser{
            id
            offer{
                id
                name
            }
        }
        parent {
            id
            username
            email
            group
            status
            offerByUser{
                id
                offer{
                    id
                    name
                }
            }
        }
        children {
            id
            username
            email
            group
            status
            offerByUser{
                id
                offer{
                    id
                    name
                }
            }
        }

    }
}