mutation AddWorker($updateWorkerData: UpdateWorkerDTO!) {
    updateWorker(updateWorkerData: $updateWorkerData){
        id
        username
        email
        group
        status
        offerByUser{
            id
            offer{
                id
                name
            }
        }
        parent {
            id
            username
            email
            group
            status
            offerByUser{
                id
                offer{
                    id
                    name
                }
            }
        }
        children {
            id
            username
            email
            group
            status
            offerByUser{
                id
                offer{
                    id
                    name
                }
            }
        }
    }
}