mutation SignUpUser($signUpData: SignUpUserDTO!) {
    signUp(signUpData: $signUpData) {
        id
        username
        isConfirmEmail
        token
        platforms{
          id
          platformName
          type
        }
    }
}